window.loadMedia=k;var r=0;
function k(a,d){r=0;d=d||function(){};for(var l=0,h="",n="",p="",q={},m=0;m<a.length;++m){var l=l+(a[m].a||1),h=a[m].src||a[m],p=a[m].name||h,n=a[m].type||s(h),g;switch(n){case "image":g=new Image(h);break;case "audio":g=new t([h]);break;case "video":g=new u(h);break;case "script":g=new v(h);break;case "text":g={},get(h,function(){r+=g.a;var a=g.name;q[a]=this.response;d(100*(r/l),a)})}g.a=a[m].a||1;g.name=p;if("audio"==n)g.b("canplaythrough",function(){r+=this.a;d(100*(r/l),this.name)},!1);else try{g.b("load",
function(){r+=this.a;d(100*(r/l),this.name)},!1)}catch(w){}q[p]=g}return q}
function s(a){var d=!1;if(0<a.lastIndexOf("."))switch(a.substring(a.lastIndexOf(".")+1)){case "jpg":case "jpeg":case "png":case "gif":case "tif":case "bmp":d="image";break;case "mp3":case "ogg":case "m4a":case "wma":case "raw":case "wav":d="audio";break;case "mp4":case "avi":case "wmv":case "mov":case "flv":case "mkv":case "mpg":case "ogv":case "webm":d="video";break;case "js":d="script";break;case "txt":case "json":d="text"}return d}HTMLElement.prototype.b=HTMLElement.prototype.addEventListener;
window.b=window.addEventListener;window.c=window.c||window.e;window.f=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||function(a){setTimeout(a,16)};function Image(a){a=a||"";var d=document.createElement("img");d.src=a;return d}var u=u||function(a){var d=document.createElement("video");d.d="auto";d.src=a;return d};
function t(a){var d=document.createElement("Audio");d.d="auto";if(a instanceof Array)for(var l=0;l<a.length;++l){var h=document.createElement("source");h.src=a[l];d.appendChild(h)}return d}function v(a){var d=document.createElement("script");d.src=a;document.head.appendChild(d);return d};
CanvasRenderingContext2D.prototype.clear=function(){this.clearRect(0,0,this.canvas.width,this.canvas.height)};
window.getById=function(a){return document.getElementById(a)};
window.getByClass=function(d,a){a=a||document;if(a.getElementsByClassName)return a.getElementsByClassName(d);for(var c=a.getElementsByTagName("*"),b=0,e=[],f=RegExp("(^|\\s)"+d+"(\\s|$)"),b=0;b<c.length;++b)null!==c[b].className.match(f)&&e.push(c[b]);return e};
window.distance=function(a,b){return Math.sqrt(Math.pow(b.x-a.x,2)+Math.pow(b.y-a.y,2))};
var M = Math;
window.get=function(b,c){var a=new XMLHttpRequest;a.open("get",b);a.onload=c;a.send();return a};
window.log=function(a){console.log(a)};